####################################################
#                      Defx
####################################################
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git",'defx-icons']
hook_add = """
  source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

####################################################
#                   Resize
####################################################
[[plugins]]
repo = 'simeji/winresizer'
# Vim Window resize
# Ctrl + E => hjkl


####################################################
#                    Appearance
####################################################
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jacoborus/tender'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:cpp_class_scope_highlight = 1   
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

####################################################
#                   Git
####################################################
[[plugins]]
repo = 'tpope/vim-fugitive'
# :Gstatus
# :Gdiff
# :Gwrite git add
# :Gblame

[[plugins]]
repo = 'airblade/vim-gitgutter'
# display git diffidence. [c & ]c is Jump hank.


####################################################
#                  Intellisense
####################################################
[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "master"
build = "yarn install --frozen-lockfile"

hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''


###################################################
#                fzf
###################################################
[[plugins]]
repo = 'junegunn/fzf'
build = './install -add'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = """
  source ~/.config/nvim/plugins/fzf.rc.vim
"""


