[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git"]

[[plugins]]
repo = 'simeji/winresizer'
# Vim Window resize
# Ctrl + E => hjkl

[[plugins]]
repo = 'tomtom/tcomment_vim'
# comment out
# Ctrl + v -> Ctrl + --

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = "['markdown', 'pandoc.markdown', 'rmd']"
build = "sh -c 'cd app & yarn install'"
# Ctrl + M

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  let g:NERDTreeQuitOnOpen = 1
'''
# Ctrl + n => Toggle

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# NERDTree showing git status flags

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
# :FixWhitespace => white space delete.

[[plugins]]
repo = 'tpope/vim-fugitive'
# :Gstatus
# :Gdiff
# :Gwrite git add
# :Gblame

[[plugins]]
repo = 'airblade/vim-gitgutter'
# display git diffidence. [c & ]c is Jump hank.

# [[plugins]]
# repo = 'kaicataldo/material.vim'

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue'
'''

[[plugins]]
repo = 'gko/vim-coloresque'

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
let g:vue_pre_processors = ['scss','typescript']
'''

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''
