[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'


[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git"]

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'simeji/winresizer'
# Window resize
# Ctrl + E => hjkl

[[plugins]]
repo = 'tomtom/tcomment_vim'
# comment out
# Ctrl + v -> Ctrl + - * 2

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = "['markdown', 'pandoc.markdown', 'rmd']"
build = "sh -c 'cd app & yarn install'"
# Ctrl + M

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  let g:NERDTreeQuitOnOpen = 1
'''
# Ctrl + n => Toggle

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# NERDTree showing git status flags

[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
# :FixWhitespace => white space delete.

[[plugins]]
repo = 'tpope/vim-fugitive'
# :Gstatus
# :Gdiff
# :Gwrite git add
# :Gblame

[[plugins]]
repo = 'airblade/vim-gitgutter'
# display git diffidence. [c & ]c is Jump hank.

[[plugins]]
repo = 'kaicataldo/material.vim'

