[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git"]

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = "['markdown', 'pandoc.markdown', 'rmd']"
build = "sh -c 'cd app & yarn install'"

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  let g:NERDTreeQuitOnOpen = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'rhysd/clever-f.vim'



