###################################################
#                    Syntax
###################################################
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
let g:vue_pre_processors = ['scss','typescript']
'''

[[plugins]]
repo = 'cespare/vim-toml'                                    

