[[plugins]]
repo = 'ryanoasis/vim-devicons'

####################################################
#                      Defx
####################################################
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git",'defx-icons']
hook_add = """
  source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

####################################################
#                   Resize
####################################################
[[plugins]]
repo = 'simeji/winresizer'
# Vim Window resize
# Ctrl + E => hjkl


####################################################
#                    Appearance
####################################################
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jacoborus/tender'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:cpp_class_scope_highlight = 1   
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

####################################################
#                   Git
####################################################
[[plugins]]
repo = 'tpope/vim-fugitive'
# :Gstatus
# :Gdiff
# :Gwrite git add
# :Gblame

[[plugins]]
repo = 'airblade/vim-gitgutter'
# display git diffidence. [c & ]c is Jump hank.

####################################################
#                   Color Code Support
####################################################
# Color Code Highlight
[[plugins]]
repo = 'gko/vim-coloresque'

# Color Picker
[[plugins]]
repo = 'KabbAmine/vCoolor.vim'

####################################################
#                  Intellisense
####################################################
[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''

####################################################
#                   Comment 
####################################################
[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
'''


####################################################
#                   Match Tags 
####################################################
[[plugins]]
repo = 'tmhedberg/matchit'

# Automatically Rename HTML Tags
[[plugins]]
repo = 'AndrewRadev/tagalong.vim'

# HTML Tag Match
[[plugins]]
repo = 'Valloric/MatchTagAlways'
hook_add = '''
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'vue' : 1,
    \}
nnoremap <leader>5 :MtaJumpToOtherTag<cr>
'''

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.xhtml,*.vue'
'''

# closing parenthesis auto input
[[plugins]]
repo = 'cohama/lexima.vim'


###################################################
#                fzf
###################################################
[[plugins]]
repo = 'junegunn/fzf'
build = './install -add'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = """
  source ~/.config/nvim/plugins/fzf.rc.vim
"""

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'marko-cerovac/material.nvim'
hook_add ='''
let g:material_style = 'Darker'
'''

[[plugins]]
repo = 'Xuyuanp/scrollbar.nvim'
