[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ["defx-git",'defx-icons']
hook_add = """
  source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'simeji/winresizer'
# Vim Window resize
# Ctrl + E => hjkl

[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'hzchirs/vim-material'
[[plugins]]
repo = 'jacoborus/tender'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:cpp_class_scope_highlight = 1   
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
set laststatus=2
let g:airline_theme = 'wombat' " Color Theme
let g:airline_powerline_fonts = 1  " Acticate powerline font
let g:airline#extensions#tabline#enabled = 1  " Activate tabs
let g:airline#extensions#tabline#buffer_idx_mode = 1 " Display tab index
" 選択行列の表示をカスタム(デフォルトだと長くて横幅を圧迫するので最小限に)
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
# :Gstatus
# :Gdiff
# :Gwrite git add
# :Gblame

[[plugins]]
repo = 'airblade/vim-gitgutter'
# display git diffidence. [c & ]c is Jump hank.

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue'
'''

[[plugins]]
repo = 'gko/vim-coloresque'

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
'''

# Color Picker
[[plugins]]
repo = 'KabbAmine/vCoolor.vim'
